version: '2'

services:
  db:
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_DB=challenge"
      - "POSTGRES_USER=challenge"
      - "POSTGRES_PASSWORD=challenge"
      - "PGDATA=/var/lib/postgresql/data/challenge"
